### ISSUE TITLE
Fails when underlying path contains space character

### ISSUE THREAD

**Issue by jefft4** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#10]
rsnapshot fails on shares whose underlying directory includes a space in the path, even if the share name has no space.

Sample error text below.  The folder is actually named "Carols Pics" on the ext4 filesystem and is defined to OMV as a share "CarolsPics".

echo 8676 > /var/run/rsnapshot-7c3191cb-5442-4cbd-9ebd-dbe9853ed7f1.pid 
/bin/rm -rf \
    /media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data//media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols \
    Pics/hourly.1/ 
native_cp_al("/media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data//media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols \
    Pics/hourly.0", \
    "/media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data//media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols \
    Pics/hourly.1") 
/usr/bin/rsync -a --delete --numeric-ids \
    /media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data//media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols \
    Pics/hourly.0/ \
    /media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data//media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols \
    Pics/hourly.1/ 
rsync: link_stat "/media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data/media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols" failed: No such file or directory (2)
rsync: change_dir "/media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data/media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols Pics//Pics/hourly.0" failed: No such file or directory (2)
rsync: link_stat "/media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data/media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols" failed: No such file or directory (2)
rsync: mkdir "/media/1b95ad16-a76e-4fdf-9279-5f7c3932a8a1/backup.data/media/c45ee932-60f9-42cb-ae54-48d67748046e/Carols Pics/Pics/hourly.1" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(605) [Receiver=3.0.9]
rsync: connection unexpectedly closed (9 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(605) [sender=3.0.9]

**Comment by ryecoaaron** [comment]
closing due to age.
