### ISSUE TITLE
Avoid "Resource limit matched" E-Mail when Rsnapshot is running

### ISSUE THREAD

**Issue by Skaronator** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#11]
Hey,

I just build my first NAS and I'm suprised how many plugins they are for OMV (good job!). Everything works fine so far but just have this little annoying thing. Everytime Rsnapshot execute the incremental backup does I get this 2 E-Mails:

> Resource limit matched Service localhost 
> 
>   Date:        Sat, 05 Mar 2016 20:07:06
>   Action:      alert
>   Host:        omv-nas.local
>   Description: loadavg(5min) of 2.2 matches resource limit [loadavg(5min)>2.0]
> 
> Your faithful employee,
> Monit

and

> Resource limit succeeded Service localhost 
> 
>   Date:        Sat, 05 Mar 2016 20:11:06
>   Action:      alert
>   Host:        omv-nas.local
>   Description: 'localhost' loadavg(5min) check succeeded [current loadavg(5min)=2.1]
> 
> Your faithful employee,
> Monit

Is it possible to mute this kind of E-Mails if Rsnapshot is running (or maybe ignore it from the process-list)?

Here are some specs of my NAS:
- 4TB Raid1
- 8TB HDD (non-Raid) for incremental backup
- Pentium G4400 + 8GB DDR3 RAM
- Backport Kernel (3.16)

**Comment by ryecoaaron** [comment]
The plugin can't change this behavior.  Not sure how you would change it on OMV either since it is just trying to detect high load.

**Comment by Skaronator** [comment]
Guessed that already. Maybe add a API to the Mailing thing called `IgnoreHighLoadProcess` and plugins can submit thier process ID **or** add to the setting page of the mailing thing a entry `Ignore high load from Plugins` and then can you select each plugin.

**Comment by ryecoaaron** [comment]
You can request that on OMV bugtracker - http://bugtracker.openmediavault.org/

**Comment by Skaronator** [comment]
alright,

hope this is fine http://bugtracker.openmediavault.org/view.php?id=1486
