### ISSUE TITLE
rsnapshot does the job even when the disk is not present

### ISSUE THREAD

**Issue by billboule** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#12]
Hello,

I'll try my best to explain the problem in English:
- set an rsnapshot task coming form a share folder in disk 1 to share folder in disk 2
- it woks fine until you disconnect disk 2
- if disk 2 is not present and cron starts for a snapshot, a folder is created on your main operating system disk in /media/UUID-of-the-disk and the snapshot is made... until your / is full ;-(

Possible fix : The program should test if the share is available before the start of the rsync....

**Comment by ryecoaaron** [comment]
This would be a major problem since OMV assumes for every plugin that the shared folder is mounted if present.  The only way to unmount a drive in the web interface is to delete the shared folder. I can look at checking in rsnapshot but this is a bigger problem.

**Comment by billboule** [comment]
what I did is:
- halt the server
- unplug the disk 2
- start the server with disk 1 only (and the SD card where debian is installed)

**Comment by ryecoaaron** [comment]
I know how to recreate it but you aren't supposed to do that and expect everything to function properly.

**Comment by billboule** [comment]
.... if you say that.... I dind't know I was doing an "illegal" action.
to me it looks like : OMV knows if the physical disk is present, and the share should be active only if the partition is mounted

**Comment by ryecoaaron** [comment]
That is a nice idea but OMV has never worked that way. The shared folder is always active. It doesn't check to make sure the drive is mounted.

**Comment by billboule** [comment]
Ok, so this is just a misunderstood on my side on how OMV works.
It looks to me that a lot of users are using removable drive in a personnal or semi-pro config (because they are using boards -like rasberry pi- or normal PC but not a real server config)
Thanks
