### ISSUE TITLE
 Invalid cross-device link

### ISSUE THREAD

**Issue by henfri** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#16]
Dear all,

thanks for this great plugin.
I found, that I am recently getting these errors:

`/bin/cp: das Erzeugen von harter Verknüpfung „/media/22cd0c22-c75b-432a-b92b-73229607a8bd/Backups/rsnapshot//media/22cd0c22-c75b-432a-b92b-73229607a8bd/Dokumente/Hendrik/HeimNetzwerk/Homeserver/daily.1/urbackup/urbackup-server_2.0.30_amd64.deb“ zu Verzeichnis „/media/22cd0c22-c75b-432a-b92b-73229607a8bd/Backups/rsnapshot//media/22cd0c22-c75b-432a-b92b-73229607a8bd/Dokumente/Hendrik/HeimNetzwerk/Homeserver/daily.0/urbackup/urbackup-server_2.0.30_amd64.deb“ ist nicht möglich: Ungültiger Link über Gerätegrenzen hinweg`

What could be the reason for this?

Regards,
Hendrik

**Comment by ryecoaaron** [comment]
What version of OMV?  What are the filesystem types of the shared folders?

**Comment by henfri** [comment]
Hello,

the OMV version is beta 3 with all updates.
The drives are combined with mergerfs to one drive. <<-- this could be the reason, don't you think? Sorry, for not mentioning it before, but I did not think of it.
The source is ext4.

**Comment by ryecoaaron** [comment]
Are both the source and destination the same mergerfs pool?

**Comment by henfri** [comment]
Hello Aaron,

yes they are.

Greetings,
Hendrik

**Comment by ryecoaaron** [comment]
Let me see if I can duplicate this.

**Comment by henfri** [comment]
Thanks, I appreciate it.
I can imagine, that it only happens, if the merger-fs strategy leads merger-fs to store the current backup at a different underlying filesystem (i.e. drive/partition, not type) than the previous backup.

**Comment by ryecoaaron** [comment]
I was able to replicate this.  You can't even rsnapshot from the source to a different mergerfs pool.  This must be due to how rsnapshot uses hard links.

**Comment by henfri** [comment]
Hello Aaron,

>You can't even rsnapshot from the source to a different mergerfs pool.

I don't understand, what you mean here.
What's the source in this case?

For hardlinks to work, the source and the target of the hardlink must be on the same filesystem. Thus, if mergerfs balancing mechanism decides to store on a different filesystem, it is bound to fail.
Generally though, mergerfs does support hard links.
See: https://github.com/trapexit/mergerfs/issues/346

Regards,
Hendrik

**Comment by ryecoaaron** [comment]
Just to rule out every combination, I created a mergerfs pool of three disks (d1,d2,d3) called pool1.  I created another mergerfs pool of two disks (d4,d5) called pool2.  I tried to rsnapshot a shared folder on pool1 to pool1.  It failed when trying to create the hard links.  I tried to rsnapshot a shared folder on pool1 to pool2.  It failed when trying to create the hard links.

**Comment by ryecoaaron** [comment]
If mergerfs always put hard links on the same drive when it encountered them, it would work well.  I just don't know if this is possible.  I guess we will see what trapexit says.

**Comment by henfri** [comment]
That is interesting.
It did run for me for quite a while without any change (except that now the drives are full). It must be related to the distribution policy. In case of "eplus" (existing path, least use space) it will work until one drive (e.g. d1) is full. Then mergerfs will create a folder under d2. From here on, the trouble will start.

I think it is best to not allow a mergerfs pool as a target.

P.S: Temporarily, I think I worked around this problem, by using the unterlying disk as a target rather than the mergerfs pool.

**Comment by ryecoaaron** [comment]
I guess I could look into what it would take to disallow mergerfs pools as a target but it would be nicer if mergerfs could just write the hard link to the same disk.

**Comment by trapexit** [comment]
If I understand the situation correctly then my suggestion is to use non-path preserving policies[0]. By doing so mergerfs will clone paths when creating links or renaming files so you won't get EXDEV errors. You'll end up with files spread out over more drives, yes, but if it's **really** an issue then create a secondary mergerfs mount for your rsnapshot which is non-path preserving and for other things where you want to preserve paths you use the other mount. I could create directory specific policies I suppose but i'm not too keen on doing so.

[0] https://github.com/trapexit/mergerfs#rename--link

**Comment by ryecoaaron** [comment]
closing due to age.
