### ISSUE TITLE
Editing the "One filesystem only" value of an entry triggers an error

### ISSUE THREAD

**Issue by pbertra** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#17]
When I try to edit a job to change the "one filesystem only" value, I get the following error: " : "onefs: The value '1' is not a boolean."

OMV version :  3.0.76
openmediavault-rsnapshot 3.8
rsnapshot 1.3.1-4+deb8u1

System is up to date.

The issue did not occur in the past.

**Comment by ryecoaaron** [comment]
Fix in 3.9.
