### ISSUE TITLE
Last commit introduce a bug

### ISSUE THREAD

**Issue by Skaronator** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#18]
@ryecoaaron

It is now generating new folder with `| uniq` in the folder name

![image](https://user-images.githubusercontent.com/2886913/31044887-6fb06e46-a5d8-11e7-91f5-95d1c3cfcc1c.png)

**Comment by ryecoaaron** [comment]
Fixed in 4.1.2.
