### ISSUE TITLE
"srcsharedfolderref: The value '' is not an UUIDv4" Error

### ISSUE THREAD

**Issue by omid-1985** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#22]
Currently mounted 4 x ext4 disks. First and second disks are Snapraid data. The third disk is Snapraid Parity and the fourth disk only mounted as a rsnapshot backup location.
Created backup from a shared folder called "Disk1" from dev/sda to "Backup" folder on dev/sdd.
Now if I click on Edit button to edit my backup job, this error comes up:
 
![image](https://user-images.githubusercontent.com/19699810/44183461-68a58880-a14e-11e8-8a78-dde6f1c8b182.png)

**Here is full error details:**

Error #0:
OMV\Json\SchemaValidationException: srcsharedfolderref: The value '' is not an UUIDv4. in /usr/share/php/openmediavault/datamodel/schema.inc:39
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(373): OMV\DataModel\Schema->checkFormat('', Array, 'srcsharedfolder...')
#1 /usr/share/php/openmediavault/json/schema.inc(297): OMV\Json\Schema->validateString('', Array, 'srcsharedfolder...')
#2 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType('', Array, 'srcsharedfolder...')
#3 /usr/share/php/openmediavault/config/datamodel.inc(155): OMV\Json\Schema->validate('', 'srcsharedfolder...')
#4 /usr/share/php/openmediavault/config/configobject.inc(189): OMV\Config\DataModel->validateProperty('srcsharedfolder...', '')
#5 /usr/share/php/openmediavault/config/configobject.inc(375): OMV\Config\ConfigObject->set('srcsharedfolder...', '')
#6 /usr/share/php/openmediavault/config/configobject.inc(338): OMV\Config\ConfigObject->reset('srcsharedfolder...')
#7 /usr/share/openmediavault/engined/rpc/rsnapshot.inc(102): OMV\Config\ConfigObject->copy('src.sharedfolde...', 'srcsharedfolder...')
#8 [internal function]: OMVRpcServiceRsnapshot->get(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('get', Array, Array)
#11 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('RSnapshot', 'get', Array, Array, 1)
#12 {main}

Here is complete report of my setup:
[content1534386363.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/files/2292234/content1534386363.txt)

**Comment by ryecoaaron** [comment]
Did you try clearing your browser cache?

**Comment by omid-1985** [comment]
@ryecoaaron 
Yes, I've reinstalled and upgraded the OMV v.4.1.9. Configured the same setup, then cleared web control panel cache with omv-firstaid. Finally cleared my browser cache and also tested with a different browser on different PC. Still the same error.

**Comment by omid-1985** [comment]
continuing my on this issue, I've removed all Snapraid drives. then configured three first drive as a RAID 5 and left forth drive for rsnapshot backup. The result is same with the same error.

Here is new setup report:
[content1534485974.txt](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/files/2296158/content1534485974.txt)

**Comment by ryecoaaron** [comment]
This is strictly an issue with editing an rsnapshot job.  None of your other config is causing this.  I can reproduce this.  Trying to figure out what is wrong.

**Comment by Macek007** [comment]
Hi, same issue... I did setup of rsnapshot job, than I wanted to edit it

version 4.1.11.
fresh install of rsnapshot plugin

![image](https://user-images.githubusercontent.com/10949306/45602326-88192500-ba1c-11e8-868d-7464f2b38f8a.png)

Error #0:
OMV\Json\SchemaValidationException: srcsharedfolderref: The value '' is not an UUIDv4. in /usr/share/php/openmediavault/datamodel/schema.inc:39
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(373): OMV\DataModel\Schema->checkFormat('', Array, 'srcsharedfolder...')
#1 /usr/share/php/openmediavault/json/schema.inc(297): OMV\Json\Schema->validateString('', Array, 'srcsharedfolder...')
#2 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType('', Array, 'srcsharedfolder...')
#3 /usr/share/php/openmediavault/config/datamodel.inc(155): OMV\Json\Schema->validate('', 'srcsharedfolder...')
#4 /usr/share/php/openmediavault/config/configobject.inc(189): OMV\Config\DataModel->validateProperty('srcsharedfolder...', '')
#5 /usr/share/php/openmediavault/config/configobject.inc(375): OMV\Config\ConfigObject->set('srcsharedfolder...', '')
#6 /usr/share/php/openmediavault/config/configobject.inc(338): OMV\Config\ConfigObject->reset('srcsharedfolder...')
#7 /usr/share/openmediavault/engined/rpc/rsnapshot.inc(102): OMV\Config\ConfigObject->copy('src.sharedfolde...', 'srcsharedfolder...')
#8 [internal function]: OMVRpcServiceRsnapshot->get(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('get', Array, Array)
#11 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('RSnapshot', 'get', Array, Array, 1)
#12 {main}

**Comment by Rizos39** [comment]
Same issue here .. jobs are executed right but can not edit them.

Version 4.1.11 (Arrakis)

Error: srcsharedfolderref: The value '' is not an UUIDv4.

`Error #0:
OMV\Json\SchemaValidationException: srcsharedfolderref: The value '' is not an UUIDv4. in /usr/share/php/openmediavault/datamodel/schema.inc:39
Stack trace:
#0 /usr/share/php/openmediavault/json/schema.inc(373): OMV\DataModel\Schema->checkFormat('', Array, 'srcsharedfolder...')
#1 /usr/share/php/openmediavault/json/schema.inc(297): OMV\Json\Schema->validateString('', Array, 'srcsharedfolder...')
#2 /usr/share/php/openmediavault/json/schema.inc(257): OMV\Json\Schema->validateType('', Array, 'srcsharedfolder...')
#3 /usr/share/php/openmediavault/config/datamodel.inc(155): OMV\Json\Schema->validate('', 'srcsharedfolder...')
#4 /usr/share/php/openmediavault/config/configobject.inc(189): OMV\Config\DataModel->validateProperty('srcsharedfolder...', '')
#5 /usr/share/php/openmediavault/config/configobject.inc(375): OMV\Config\ConfigObject->set('srcsharedfolder...', '')
#6 /usr/share/php/openmediavault/config/configobject.inc(338): OMV\Config\ConfigObject->reset('srcsharedfolder...')
#7 /usr/share/openmediavault/engined/rpc/rsnapshot.inc(102): OMV\Config\ConfigObject->copy('src.sharedfolde...', 'srcsharedfolder...')
#8 [internal function]: OMVRpcServiceRsnapshot->get(Array, Array)
#9 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
#10 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('get', Array, Array)
#11 /usr/sbin/omv-engined(536): OMV\Rpc\Rpc::call('RSnapshot', 'get', Array, Array, 1)
#12 {main}`

Thanks in advance :-) !!

**Comment by Rizos39** [comment]
Just to have all togheter this [entry in the forum](https://forum.openmediavault.org/index.php/Thread/24115-srcsharedfolderref-The-value-is-not-an-UUIDv4-in-rsnapshot/) is about the same issue.

**Comment by ryecoaaron** [comment]
As I posted in this issue and the forum, it is a known.  I haven't had a chance to figure out what is causing it.  I can easily reproduce it.  So, no need to keep posting debug output.

**Comment by ryecoaaron** [comment]
Fixed in 4.2.1.
