### ISSUE TITLE
Incremental backup not working

### ISSUE THREAD

**Issue by pravussum** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#23]
I created a rsnapshot job via web interface (fresh install of debian via netinstall + current version of openmediavault installed) an realized during the backup that rsync is not creating hardlinks even if the files from the previous and the current backup are obviously the same (same size, date, permissions...). Inodes of the files are different (I checked with ls -i). 

Further investigation showed that rsync is called without link-dest parameter and again this is due to the fact that the rsnapshot configuration which is created in /var/lib/openmediavault/rsnapshot.d/{generatedId}.conf doesn't contain the line "link_dest 1".

I'd excpect it to be there... otherwise it's not possible to create incremental backups since there isn't an option for it in the web interface.

I just migrated from OMV3 on a different machine where this was working if I'm not totally mistaken.

**Comment by ryecoaaron** [comment]
The plugin has never had link_dest and it works on my systems.  rsnapshot will try to create hard links without it.  From the man page, this option shifts the work from cp to rsync and should only be needed on non-Linux filesystems.  I'm guessing you are using ntfs or something?

If you really need this, you could add it to the rsync long arguments box on the job settings.

**Comment by pravussum** [comment]
From my understanding rsnapshot is just calling rsync and apart from some folder renaming doesn't do much by itself. 
I thought about your suggestion es well (adding it to long args), but the thing is: the link-dest=DIR param expects the "original" directory which is kind of dynamic (especially if some of the daily snapshots are missing, e.g. when the backup was not running for some reason).
I don't fully get what you mean by "shifts the work from cp to rsync" - could you please elaborate?

**Comment by ryecoaaron** [comment]
The whole idea of rsnapshot is to use hard links. The second sentence on the rsnapshot home page says:
> The code makes extensive use of hard links whenever possible, to greatly reduce the disk space required.

As for the shifts comment, I was taking it from the rsnapshot man page.  Here is exactly what it says:

link_dest 1
If your version of rsync supports --link-dest (2.5.7 or newer), you can enable this to let rsync handle some things that GNU cp or the built-in subroutines would otherwise do. Enabling this makes rsnapshot take a slightly more complicated code branch, but it's the best way to support special files on non-Linux systems.

**Comment by pravussum** [comment]
yes, but it also says (e. g. in /etc/rsnapshot.conf):
# If your version of rsync supports --link-dest, consider **enabling** this.
# This is the best way to support special files (FIFOs, etc) cross-platform.
# The default is 0 (off).
#
#link_dest      0

And this is exactly what I experience. I also thought this to be the absolute basic for rsnapshot, but it just doesn't seem to work.
Btw, my shares are mounted as ext4. 

Could you please confirm that you have NO line "link_dest 1" in your /var/lib/openmediavault/rsnapshot.d/{generatedId}.conf (and link_dest  parameter commented out or set to 0 in /etc/rsnaphot.conf for that matter) and that the inodes of an unchanged file in two consecutive backups are the same (by ls -i)?

**Comment by pravussum** [comment]
This seems to have been some sort of side effect migrating the backup from OMV 3 to 4. Coincidentally my main drive crashed a couple of days ago and I reconfigured the rsnapshot backup on two new disk and voila: it works as expected.
