### ISSUE TITLE
rsnapshot plug in for omv5 fails to create backups

### ISSUE THREAD

**Issue by gzukunft** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#25]
Hi,

just installed the rsnapshot plug in (OMV5) and created a backup routine.

You can start the backup task without an error message. No backup is created. The routine starts and ends immediately.
I double checked the UI entries such as source and destination folders. I cannot find anything that I should change.
OMV 5 itself runs since weeks without problems on my nas.

Regards, Gunnar

**Comment by ryecoaaron** [comment]
5.0.1 in the repo now.
