### ISSUE TITLE
Separate cron jobs for each Rsnapshot entries

### ISSUE THREAD

**Issue by Eurbaix** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#28]
In some cases, like creating a snapshop of a database used by a Docker container, it's preferable to stop the container before the snapshot and restarting the container when it's done. If there are other large snapshots defined (like you movie or music collection), it's really hard to predict when the database snapshot will be completed.

With the ability to define a specific time of day, or day of week, for each snapshot, we would be able to define a specific time where only the database snapshot is running, estimate the maximum duration for a full snapshot, and define stop/start cron jobs accordingly, without having a multi-TB snapshot delaying the database snapshot by several hours (or days in case of a full snapshot of several TB on a remote mount).

P.S.: Maybe you can reuse some of the code of the Rsync plugin, which define a separate cron job for each entry. It would probably still be a major job, but not being able to know when snapshots are actually occurring is a major problem (not just for databases, but also if the snapshot is still bogging the CPU and/or disks in the evening when you want to watch a movie).

**Comment by ryecoaaron** [comment]
Since the rsnapshot plugin is really designed to run hourly, this is something I will not be adding.  The pre-exec and post-exec options will have to work.  I would recommend separating the movie/music snapshot from the database snapshot.

**Comment by Eurbaix** [comment]
> The pre-exec and post-exec options will have to work.

This could work (if the database snapshot is the first one defined in the plugin so NextCloud doesn't stop in the middle of the day), but cmd_preexec and cmd_postexec are not exposed in the plugin. Adding them manually means digging in configuration files and uuids, which is not ideal for obvious reasons.

Could you add the cmd_preexec and cmd_postexec in the plugin interface? I would create another issue in that case since it has nothing to do with scheduling.

**Comment by ryecoaaron** [comment]
> cmd_preexec and cmd_postexec are not exposed in the plugin.

Umm, yes they are.  They are the last two fields when creating a job.

**Comment by Eurbaix** [comment]
They were not yet on 4.2.1 which is the last stable version for OMV 4.x. I guess I'll have to upgrade to OMV 5.x at one point.

I guess this can be closed now since Rsnapshot for OMV 5.x will solve it.

**Comment by ryecoaaron** [comment]
I added the code - https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/commit/d4cb3b2cd26e1267759a1d3d847844c716eb63ef -  to the 4.x plugin over a year ago but I guess I never pushed it out.  I can look at doing that when I get a chance.

**Comment by Eurbaix** [comment]
Thanks. That would help. I'd like to have a backup that can be restored easily and quickly before I migrate to 5.x (you never know!) and rsnapshot is really the ideal solution for plucking the disk(s) out of the backup server and restoring the main NAS at eSATA speed. Thanks for developing the plugin by the way.
