### ISSUE TITLE
Comment field seems to be required but does not give feedback/signal it is

### ISSUE THREAD

**Issue by TERLENtA** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#29]
Although commentfield (or name) only shows up in commentfield it seems not to be necessary to fill. 

When leaving the comment-field empty it blocks the input/creating of a rSnapshot job and exits with error 400 (empty string) without leaving a notice to the user that the error occurs because of that empty commentfield. Activating the field during input seems to solve the problem.

Expected behaviour: commentfield should not be required for completing and creating a new job.

**Comment by ryecoaaron** [comment]
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/commit/1ad81d92115487bc8cfae38093a7c192b8f8abea
