### ISSUE TITLE
Link in readme 404s

### ISSUE THREAD

**Issue by chocmake** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#30]
Seems the forum at some point must have changed the URL scheme and the link in the readme 404s. Afaict [this](https://forum.openmediavault.org/index.php?thread/2726/) is the same thread that was being linked to.

Just thought I'd give a heads-up.

**Comment by ryecoaaron** [comment]
Thanks.  I updated the readme and removed the link.  That thread is very old.  The plugin will get a link to the omv-extras wiki once the wiki page is written.
