### ISSUE TITLE
Installation caused all other OMV Extras plugins, OMV web UI and shares to error

### ISSUE THREAD

**Issue by chocmake** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#31]
This is a strange one. Was running OMV 6 with latest updates.

- I installed the plugin via the Plugins menu in OMV's web UI.
- It completed with a 'connection lost' and marked the plugin as installed immediately following.
- The plugin didn't seem to appear in OMV's web UI so I rebooted OMV via the web UI.
- Took longer to reboot the system than normal then when in the OMV web UI none of OMV Extras related menus opened, instead showing OMV's 404 error (with the black screen and red text).
    - This was the case for the *System>OMV Extras*, *System>Kernel*, *Services>Rsnapshot* (that now appeared), *Storage>mergerfs* menu items.
 
I checked the *Diagnostics>System Logs>Rsnapshot* item and an error popup appeared:
 ```
     SplFileObject::__construct(/var/log/rsnapshot.log): failed to open stream: No such file or directory

    RuntimeException: SplFileObject::__construct(/var/log/rsnapshot.log): failed to open stream: No such file or directory in /usr/share/openmediavault/engined/rpc/logfile.inc:82
    Stack trace:
    #0 /usr/share/openmediavault/engined/rpc/logfile.inc(82): SplFileObject->__construct('/var/log/rsnaps...', 'r')
    #1 [internal function]: Engined\Rpc\LogFile->getList(Array, Array)
    #2 /usr/share/php/openmediavault/rpc/serviceabstract.inc(123): call_user_func_array(Array, Array)
    #3 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod('getList', Array, Array)
    #4 /usr/sbin/omv-engined(537): OMV\Rpc\Rpc::call('LogFile', 'getList', Array, Array, 1)
    #5 {main}
 ```
 
At this point I removed the plugin via the web UI then rebooted.
 
 - Following the reboot OMV's web UI wouldn't load, instead showing OMV's 503 error page (black screen/red text). About 5 minutes later only the native, generic browser `ERR_CONNECTION_TIMED_OUT` error page appeared when loading OMV's static IP.
 - None of the shares were accessible and neither was SSH.
 
I then hard shutdown the system and booted again and this time things were back to normal.
 
---

I had installed the Proxmox kernel v6.1 via the Kernel plugin the day prior. Would that have made any difference?

**Comment by ryecoaaron** [comment]
Connection lost is normal when installing a plugin because omv-engined is restarted. Did you try ctrl-shift-R?  The log issue is known issue with OMV (not just the plugi ) because no log file exists yet. The proxmox kernel would not make a difference other than boot time but that issue is not related to rsnapshot.

**Comment by chocmake** [comment]
> Did you try ctrl-shift-R

For force reloading the web page? Almost sure I did it in the 404 instances but definitely for the 503 cases. Though during the 503 errors even SSH wouldn't connect. Seems strange the 503 would occur *after* uninstalling the plugin but idk what occurred.

I might try a different kernel just to rule it out and re-install the plugin and see what happens.

**Comment by chocmake** [comment]
> Is this a new install that you installed with no internet connection?

It was new install of Rsnapshot if that's what you mean, but I was connected online to install the plugin via the web UI. Also was connected online to install OMV itself when doing so and hadn't experienced these issues previously.

Found when booting OMV today that I couldn't connect to either the web UI, SSH or SMB, similar to the issue from the OP following the plugin uninstallation (was working the last boot though as per the OP). So shutdown the OMV and I connected directly to it via a display cable and ran `apt-get update` and `apt-get upgrade` as per the official docs.

It said following the updates the `/etc/default/openmediavault`  configuration file was modified and prompted whether I wanted to use the package maintainer's version or the existing confg file, or show the difference. So I looked at the diff and among a handful of other lines it showed three Rsnapshot lines:

```
-OMV_RSNAPSHOT_CONFS_DIR="/var/lib/...
-OMV_RSNAPSHOT_CRONSCRIPT="...
-OMV_STARTING_HOUR="...
```
(Going off written notes since my camera unfortunately acting up)

I chose to keep the current config (`N` option).

---

After reboot I could successfully connect to everything again. I rebooted again just to double-check and similarly was fine. Haven't tested re-installing the plugin yet.

**Comment by chocmake** [comment]
Tried installing the plugin again and haven't run into any issues, thankfully.

- Went into *System>omv-extras* and clicked 'apt clean' button.
- Went into *System>Plugins* and installed `openmediavault-rsnapshot 6.0.2`. This time didn't have any connection lost line just 'End of line' (though from what you've said it makes no difference).
- *Services>Rsnapshot* appeared immediately following and I didn't have any issues clicking OMV Extras related menu items.

Rebooted and similarly everything seems intact. So idk if it was just the extra apt-get update + upgrade that ended up resolving it. Hopefully some of the troubleshooting documented is of use to anyone experiencing something similar in the future though.
