### ISSUE TITLE
Setting custom OMV_RSNAPSHOT_STARTING_HOUR isn't triggering snapshot

### ISSUE THREAD

**Issue by chocmake** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#32]
According to [this thread](https://forum.openmediavault.org/index.php?thread/43217-rsnapshot-plugin-scheduling-and-timing/) an OMV moderator mentioned the hour Rsnapshot is run for the default daily backup schedule can be changed by adjusting the `OMV_RSNAPSHOT_STARTING_HOUR` environment variable via SSH.

- I first checked the value using `omv-env get OMV_RSNAPSHOT_STARTING_HOUR` which reported as `2` (so 2AM afaict).

- Then changed the value using: `omv-env set OMV_RSNAPSHOT_STARTING_HOUR <hour>` which then reported as being the new value when checking via `omv-env get` again.

- Following this I entered these commands as root as per the OMV 6 docs to apply new changes:
```
monit restart omv-engined
omv-salt stage run prepare
omv-salt stage run deploy
```

I then waited for the upcoming hour but Rsnapshot didn't trigger a snapshot. I'd read you mention on the OMV forum that for hourly snapshots at least it waits an additional 5 minutes before triggering. So I waited longer but it still didn't trigger.

Also checked the NAS' internal clock using `date` and it matched. OMV's web UI *Diagnostics* logs for Rsnapshot didn't show anything had run either.

Am I missing something with why setting this variable didn't trigger the daily snapshot? I can manually run them no problem, which is what I've so far been doing for testing.

Fwiw *System>Scheduled Tasks* doesn't show any items so had assumed Rsnapshot handles scheduling on its own behind the scenes.

**Comment by chocmake** [comment]
> I can manually run them no problem, which is what I've so far been doing for testing.

Should note that while the snapshot completes and handles the snapshot rotation (`daily.0` -> `daily.1`, etc) the native output log message contains:

```
rsnapshot encountered an error! The program was invoked with these options:
            /usr/bin/rsnapshot -c \
                /var/lib/openmediavault/rsnapshot.d/rsnapshot-33fe4bb6-7e99-4746-a9b8-1b3eb42b1a43.conf \
                daily 
```
Not sure if this is relevant. My Rsnapshot item has the default *Retain* fields (hourly: `0`, daily: `7`, monthly: `3`, yearly: `0`).

**Comment by ryecoaaron** [comment]
The changes you have made just make the value available to the plugin and saltstack. Nothing has triggered a change to rewrite the cron file /etc/cron.d/openmediavault-rsnapshot.  Run:  sudo omv-salt deploy run rsnapshot

**Comment by chocmake** [comment]
[Looking](https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/blob/master/usr/sbin/omv-rsnapshot-conf#L51) at `sbin/omv-rshapshot-conf` I notice it sets the variable used for the cron file as `+ 1` to the provided `OMV_RSNAPSHOT_STARTING_HOUR`.

So I suppose this is why it didn't trigger as it's actually set to the next hour?

**Comment by ryecoaaron** [comment]
It only adds 1 for daily and weekly.  If you look at /etc/cron.d/openmediavault-rsnapshot, you will see the hour each runs.

Probably.

And no, you can't edit the cron file unless you don't make changes to the plugin.  Why do you need such an exact time for each task?
