### ISSUE TITLE
Source folder as a subfolder

### ISSUE THREAD

**Issue by privatesam** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#34]
Is it possible for the source folder to be a sub-directory (sub-folder) of a shared folder?  For example I have a "Movies" shared folder and within that sub folders "RecordedTV" and "DVDs" and I only want to back up "DVDs"?

Thanks in advance.

**Comment by votdev** [comment]
> Is it possible for the source folder to be a sub-directory (sub-folder) of a shared folder? For example I have a "Movies" shared folder and within that sub folders "RecordedTV" and "DVDs" and I only want to back up "DVDs"?

Shared folders are the fundamental building block in OMV's concept. Therefore no plugins should introduce other concepts. You can simply create a new shared folder `DVDs` that can be used to create a new rsnapshot task.

**Comment by privatesam** [comment]
OK thanks for the answer.  Not sure sub-folders would be classed as a "other concepts" but I'm sure there might be a technical reason which makes it more complicated for the plugin to incorporate them.  I'll jut use a cronjob instead.  Thanks.

**Comment by ryecoaaron** [comment]
I don’t understand why you dont want to just create another shared folder for the subfolder?

sf1 would be /path
sf2 would be /path/sub1

then just use sf2 instead of sf1 in the rsnapshot job.
