### ISSUE TITLE
rsnapshot.conf doesn't update after updating shared folders definition

### ISSUE THREAD

**Issue by ers4691** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#35]
Hi,
in OMV (7.1.1-1) you are able to change a "shared folder" definition, for example you can change the file system. 
If you do so and the shared folder is part of a rsnapshot source/target rsnapshot will still use the old definition of the shared folder, as in  the generated rsnapshot.conf file the "shared folder" definition is hard coded into the file.
My expectation would be that the new file system definition of the shared folder is automatically adjusted in the config file.

**Comment by ryecoaaron** [comment]
The plugin has a sharedfolder listener.  I will have to figure out why it isn't working.
https://github.com/OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot/blob/master/usr/share/openmediavault/engined/module/rsnapshot.inc#L61

**Comment by ers4691** [comment]
Maybe this is relevant.
I have changed the shared folder from a local directory to a remote mount, which I had created with the remote mount plugin

**Comment by ryecoaaron** [comment]
So, you didn't actually change the shared folder and changed the remotemount?

**Comment by ryecoaaron** [comment]
Does the following fix it?  sudo omv-salt deploy run rsnapshot

I still need to look why it isn't marking the rsnapshot module dirty when you are doing this.

**Comment by ers4691** [comment]
Yes.
That changed the rsnapshot.conf File to the correct snapshot_root
Thanks, perfect.

I had changed the shard folder again and re-entered the remote mount.
I got the following error message when saving.

Failed to set file group to 'users' for '/srv/remotemount/BackupServer/Backup/': Unknown error

OMV\Exception: Failed to set file group to 'users' for '/srv/remotemount/BackupServer/Backup/': Unknown error in /usr/share/openmediavault/engined/rpc/sharemgmt.inc:411
Stack trace:
#0 [internal function]: Engined\Rpc\ShareMgmt->set()
#1 /usr/share/php/openmediavault/rpc/serviceabstract.inc(122): call_user_func_array()
#2 /usr/share/php/openmediavault/rpc/rpc.inc(86): OMV\Rpc\ServiceAbstract->callMethod()
#3 /usr/sbin/omv-engined(544): OMV\Rpc\Rpc::call()
#4 {main}

Is this the reason?

**Comment by ryecoaaron** [comment]
A shared folder on a remote mount tries to ensure the folder exists with the correct permissions.  Depending on the remote mount type and permissions, OMV will fail trying trying to set permissions.

**Comment by ers4691** [comment]
I changed the group on my remote server manually.
Should I try the changing of the shared folder again, just to make sure if this was the reason

**Comment by ers4691** [comment]
no, it didn't had any influence on the actual issue.
Changing the "shared folder" back to the local filesystem, didn't change the rsnapshot.config.

 however, your workaround worked.

**Comment by ryecoaaron** [comment]
We have two issues here.  One is a shared folder change marking the rsnapshot module dirty.  That is an rsnapshot plugin issue.

The other is the shared folder on remote mount issue.  That is a remote server permissions issue.  I don't know how to fix that one.  nfs shouldn't have the issue but cifs could.

**Comment by ryecoaaron** [comment]
7.0.1 is in the repo

**Comment by ers4691** [comment]
Thanks a lot!
