### ISSUE TITLE
disabling hourly on one job will prevent other hourly jobs from being run

### ISSUE THREAD

**Issue by Bart39** [OpenMediaVault-Plugin-Developers/openmediavault-rsnapshot#8]
due to the way /var/lib/openmediavault/cron.d/rsnapshot is compiled by the jobs settings if you configure one job not to run hourly then any further hourly jobs are not run
as soon as it hits the first `if [ "$1" = "hourly" ]; then exit 0; fi` it will exit the script ignoring any others.
same applies for any of the other frequencies
easily reproducable by creating 2 jobs and set hourly to 0 on the first job and 4 on the 2nd job - the 2nd job will never be run

**Comment by bobafetthotmail** [comment]
In case you want to contribute a fix, the file generating the content of that script is usr/share/openmediavault/mkconf/rsnapshot

**Comment by ryecoaaron** [comment]
Fix in 1.0.9 in repo now.

**Comment by ryecoaaron** [comment]
1.0.9 caused an email to be sent every hour.  1.0.10 should fix that.

**Comment by ryecoaaron** [comment]
Let's try that again.  1.0.11 should fix that.
